# Generated by Django 5.2.1 on 2025-05-27 10:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('LinearRegression', 'Linear Regression'), ('DecisionTree', 'Decision Tree'), ('KNN', 'K-Nearest Neighbors')], max_length=50)),
                ('target_column', models.CharField(max_length=100)),
                ('features', models.TextField(blank=True, null=True)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='models/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
