# Generated by Django 5.2.1 on 2025-05-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trained_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
