# Generated by Django 5.2.1 on 2025-05-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trained_model', '0002_trainedmodel_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='model_name',
            field=models.CharField(default='Demo', max_length=100),
            preserve_default=False,
        ),
    ]
