# Generated by Django 5.2.1 on 2025-05-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trained_model', '0003_trainedmodel_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='polynomial_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainedmodel',
            name='model_type',
            field=models.CharField(choices=[('LinearRegression', 'Linear Regression'), ('PolynomialRegression', 'Polynomial Regression'), ('DecisionTree', 'Decision Tree'), ('KNN', 'K-Nearest Neighbors')], max_length=50),
        ),
    ]
