# Generated by Django 5.2.1 on 2025-06-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trained_model', '0004_trainedmodel_polynomial_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
