# Generated by Django 5.2.1 on 2025-06-08 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trained_model', '0005_trainedmodel_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('graph_image', models.ImageField(blank=True, null=True, upload_to='graphs/')),
                ('graph_json', models.TextField(blank=True, null=True)),
                ('trained_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='trained_model.trainedmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r2_score', models.FloatField(blank=True, null=True)),
                ('mse', models.FloatField(blank=True, null=True)),
                ('mae', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('trained_model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='trained_model.trainedmodel')),
            ],
        ),
    ]
