# Generated by Django 5.2.1 on 2025-06-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trained_model', '0006_modelgraph_modelstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainedmodel',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='data/'),
        ),
    ]
